const questions = [
    { id: 1, question: "What is the capital of France?", options: ["Berlin", "Madrid", "Paris", "Rome"], correctIndex: 2 },
    { id: 2, question: "What is 12 × 12?", options: ["124", "144", "132", "156"], correctIndex: 1 },
    { id: 3, question: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], correctIndex: 2 },
    { id: 4, question: "What is H₂O commonly known as?", options: ["Oxygen", "Hydrogen", "Water", "Carbon dioxide"], correctIndex: 2 },
    { id: 5, question: "How many continents are there?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { id: 6, question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctIndex: 3 },
    { id: 7, question: "Who wrote 'Romeo and Juliet'?", options: ["Dickens", "Shakespeare", "Twain", "Austen"], correctIndex: 1 },
    { id: 8, question: "What gas do plants absorb?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], correctIndex: 2 },
    { id: 9, question: "What is the speed of light (approx)?", options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "100,000 km/s"], correctIndex: 0 },
    { id: 10, question: "Which element has the symbol 'O'?", options: ["Gold", "Osmium", "Oxygen", "Iron"], correctIndex: 2 },
    { id: 11, question: "What is 7 × 8?", options: ["54", "56", "58", "62"], correctIndex: 1 },
    { id: 12, question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { id: 13, question: "What is the boiling point of water in °C?", options: ["90", "100", "110", "120"], correctIndex: 1 },
    { id: 14, question: "Which country has the most people?", options: ["USA", "India", "China", "Brazil"], correctIndex: 1 },
    { id: 15, question: "What is the square root of 64?", options: ["6", "7", "8", "9"], correctIndex: 2 },
    { id: 16, question: "What is the hardest natural substance?", options: ["Gold", "Iron", "Diamond", "Platinum"], correctIndex: 2 },
    { id: 17, question: "Which animal is the tallest?", options: ["Elephant", "Giraffe", "Horse", "Camel"], correctIndex: 1 },
    { id: 18, question: "What is 15% of 200?", options: ["25", "30", "35", "40"], correctIndex: 1 },
    { id: 19, question: "What year did World War II end?", options: ["1943", "1944", "1945", "1946"], correctIndex: 2 },
    { id: 20, question: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], correctIndex: 2 },
    { id: 21, question: "How many bones are in the adult human body?", options: ["186", "206", "226", "256"], correctIndex: 1 },
    { id: 22, question: "What is the largest planet in our solar system?", options: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctIndex: 1 },
    { id: 23, question: "Who painted the Mona Lisa?", options: ["Van Gogh", "Picasso", "Da Vinci", "Monet"], correctIndex: 2 },
    { id: 24, question: "What is the freezing point of water in °F?", options: ["0", "32", "100", "212"], correctIndex: 1 },
    { id: 25, question: "What language has the most native speakers?", options: ["English", "Spanish", "Hindi", "Mandarin"], correctIndex: 3 },
    { id: 26, question: "What is 2 to the power of 10?", options: ["512", "1000", "1024", "2048"], correctIndex: 2 },
    { id: 27, question: "Which organ pumps blood in the body?", options: ["Brain", "Liver", "Heart", "Lungs"], correctIndex: 2 },
    { id: 28, question: "What is the smallest prime number?", options: ["0", "1", "2", "3"], correctIndex: 2 },
    { id: 29, question: "What continent is Egypt in?", options: ["Asia", "Europe", "Africa", "South America"], correctIndex: 2 },
    { id: 30, question: "What does CPU stand for?", options: ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Central Program Utility"], correctIndex: 1 },
    { id: 31, question: "How many minutes are in one day?", options: ["1240", "1440", "1640", "1340"], correctIndex: 1 },
    { id: 32, question: "What is the main gas in Earth's atmosphere?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correctIndex: 2 },
    { id: 33, question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Mercury"], correctIndex: 1 },
    { id: 34, question: "What is 999 + 1?", options: ["1000", "999", "1001", "9991"], correctIndex: 0 },
    { id: 35, question: "What shape has 3 sides?", options: ["Square", "Pentagon", "Triangle", "Hexagon"], correctIndex: 2 },
];

export default questions;
